export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const ADDLICENSE = "ADDLICENSE";
export const REMOVELICENSE = "REMOVELICENSE";
export const SEARCHCLIENT = "SEARCHCLIENT";
export const PLACESLIST = "PLACESLIST";
export const CATEGORIESLIST = "CATEGORIESLIST";
export const CATEGORYVSPLACE = "CATEGORYVSPLACE";
export const SERVICESLIST = "SERVICESLIST";
export const EVENTSLIST = "EVENTSLIST";
export const UPDATECOMPANYDATA = "UPDATECOMPANYDATA";
export const SERVIZIOVERVIEW = "SERVIZIOVERVIEW";
export const LISTANOMISEDI = "LISTANOMISEDI";
export const UPDATESIDEBAR = "UPDATESIDEBAR";
export const CLIENTTEMPLATEWINDOWSSERVICES = "CLIENTTEMPLATEWINDOWSSERVICES";
export const CLIENTTEMPLATEWINDOWSEVENTS = "CLIENTTEMPLATEWINDOWSEVENTS";
export const CLIENTTEMPLATEINFO = "CLIENTTEMPLATEINFO";
export const CLIENTTEMPLATEDRIVES = "CLIENTTEMPLATEDRIVES";
export const CLIENTTEMPLATEALERT = "CLIENTTEMPLATEALERT";
export const CLIENTTEMPLATEHISTORY = "CLIENTTEMPLATEHISTORY";
export const CLIENTTEMPLATEOVERVIEW = "CLIENTTEMPLATEOVERVIEW";
export const CLIENTTEMPLATERESET = "CLIENTTEMPLATERESET";
export const COMPANYTEMPLATELICENZE = "COMPANYTEMPLATELICENZE";
export const UPDATECLIENTOVERVIEW = "UPDATECLIENTOVERVIEW";
export const UPDATECOMPANYOVERVIEW = "UPDATECOMPANYOVERVIEW";
export const FIXSEDI = "FIXSEDI";







